DROP TABLE IF EXISTS mkt_project_use_scope;
CREATE TABLE `mkt_project_use_scope` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自主主键',
  `project_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '商家营销方案ID',
  `deal_type` int(11) NOT NULL DEFAULT '0' COMMENT '1:本地单,2:物流单',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '更新时间',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号',
  `yn` int(11) NOT NULL DEFAULT '1' COMMENT '1，可用。0不可用',
  PRIMARY KEY (`id`)
)  COMMENT='方案券使用范围关系表';

DROP TABLE IF EXISTS REFUND_ORDER;
CREATE TABLE REFUND_ORDER
(
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  REFUND_ORDER_ID VARCHAR(32) NOT NULL COMMENT '退款订单号',
  LOAN_ORDER_ID VARCHAR(32) NOT NULL COMMENT '原放款订单号',
  BID BIGINT NOT NULL COMMENT '百度ID',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  PRODUCT_ID VARCHAR(32) NOT NULL COMMENT '产品ID',
  PROJECT_ID VARCHAR(32) NOT NULL COMMENT '项目ID',
  STATUS INT NOT NULL COMMENT '订单状态',
  CORE_TRANSACTION_ID BIGINT NOT NULL COMMENT '核心退款交易ID',
  AMOUNT BIGINT NOT NULL COMMENT '订单金额(分)',
  PAID_AMOUNT BIGINT NOT NULL COMMENT '实际支付金额(分)',
  CONSUME_AMOUNT BIGINT NOT NULL COMMENT '已消费金额(分)（BSHOP）',
  DISCOUNT_AMOUNT BIGINT NOT NULL COMMENT '应退贴息金额(分)',
  LOAN_CORP INT NOT NULL COMMENT '放贷主体',
  REFUND_TYPE int(11) unsigned NOT NULL DEFAULT '0' COMMENT '退款类型  1:全部退   2:部分退   3:用户确认的部分退',
  REFUND_WAY int(11) unsigned NOT NULL DEFAULT '1' COMMENT '退款方式  1：商户主动打钱方式   2：放款轧差的方式',
  AUDIT_STATUS int(11) unsigned NOT NULL DEFAULT '0' COMMENT '审核状态  0：待审核  1：审核失败   2：审核成功',
  EXPIRE_TIME TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '失效时间   默认值为1970-01-01 00:00:00 永久有效',
  REPAY_BALANCE bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '核心剩余应还余额',
  MERCHART_CODE VARCHAR(32) NOT NULL COMMENT '商户号',
  PRIMARY KEY(ID),
  INDEX IDX_REFUND_ORDER_LOAN_ORDER_ID(LOAN_ORDER_ID),
  INDEX IDX_REFUND_ORDER_BID(BID),
  INDEX IDX_REFUND_ORDER_CUSTOMER_ID(CUSTOMER_ID),
  UNIQUE IDX_REFUND_ORDER_ID(REFUND_ORDER_ID)
)