/**
 * 
 */
package io.ninja.park.model;

import java.util.Date;

/**
 * @author romgzy
 *
 */
public class ProjectUseScope {
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mkt_project_use_scope.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mkt_project_use_scope.project_id
     *
     * @mbggenerated
     */
    private Long projectId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mkt_project_use_scope.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mkt_project_use_scope.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mkt_project_use_scope.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mkt_project_use_scope.yn
     *
     * @mbggenerated
     */
    private Integer yn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mkt_project_use_scope
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mkt_project_use_scope.id
     *
     * @return the value of mkt_project_use_scope.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mkt_project_use_scope.id
     *
     * @param id the value for mkt_project_use_scope.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mkt_project_use_scope.project_id
     *
     * @return the value of mkt_project_use_scope.project_id
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mkt_project_use_scope.project_id
     *
     * @param projectId the value for mkt_project_use_scope.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mkt_project_use_scope.create_time
     *
     * @return the value of mkt_project_use_scope.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mkt_project_use_scope.create_time
     *
     * @param createTime the value for mkt_project_use_scope.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mkt_project_use_scope.update_time
     *
     * @return the value of mkt_project_use_scope.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mkt_project_use_scope.update_time
     *
     * @param updateTime the value for mkt_project_use_scope.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mkt_project_use_scope.version
     *
     * @return the value of mkt_project_use_scope.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mkt_project_use_scope.version
     *
     * @param version the value for mkt_project_use_scope.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mkt_project_use_scope.yn
     *
     * @return the value of mkt_project_use_scope.yn
     *
     * @mbggenerated
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mkt_project_use_scope.yn
     *
     * @param yn the value for mkt_project_use_scope.yn
     *
     * @mbggenerated
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("MktProjectUseScope [id=");
		builder.append(id);
		builder.append(", projectId=");
		builder.append(projectId);
		builder.append(", createTime=");
		builder.append(createTime);
		builder.append(", updateTime=");
		builder.append(updateTime);
		builder.append(", version=");
		builder.append(version);
		builder.append(", yn=");
		builder.append(yn);
		builder.append("]");
		return builder.toString();
	}
    
    
}
